
version: build{build}
image: Visual Studio 2019
clone_folder: C:\CKli-World\CK-Core-Projects\CK-UnitsOfMeasure
branches:
  only:
    - master
    - develop
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
artifacts:
  - path: '**\*.log'
    name: Log file
  - path: '**\*.trx'
    name: Visual studio test results file
  - path: '**\Tests\**\TestResult*.xml'
    name: NUnit tests result files
  - path: '**Tests\**\Logs\**\*'
    name: Log files
